/**
 * ============================================================================
 *  DASHBOARD CONFIGURATION
 *  Fill these in after deploying the Apps Script Web App.
 * ============================================================================
 */
const APP_CONFIG = {
  // Paste the Web App URL from Deploy > New deployment > Web app.
  // Must end in /exec (not /dev).
  API_BASE_URL: 'https://script.google.com/macros/s/AKfycbwTrNi3GJppj4uZV7Ab16K3kz2nT8Yt8J0LbCiF8gp8loudD5GxY9y0eT1qGPKiD90/exec?action=orders',

  // Must match the value generated by setupApiKey() in Code.gs
  // (stored in Script Properties as CAFETERIA_API_KEY).
  API_KEY: '8768ced3-7ab1-49f5-8b44-937a3d204340',

  // How often to poll for new/updated orders, in milliseconds.
  POLL_INTERVAL_MS: 5000,

  // Max orders requested per poll (keeps JSON payloads small).
  ORDERS_LIMIT: 100
};
